name: Add milestone to new PRs
on:
  pull_request:
    types: [opened]

jobs:
  add-milestone:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'ornl-next') }}
    runs-on: ubuntu-latest
    steps:
      - uses: benelan/milestone-action@v3
        with:
          farthest: false      # false = use current milestone by due date
          overwrite: false     # don't overwrite if milestone already exists
